# Generated by Django 6.0.6 on 2026-06-07 03:10

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_click_shorturl_delete_urldata_click_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(default=shortener.models.default_expiry),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
